/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/authority/authority': RouteRecordInfo<'/admin/authority/authority', '/admin/authority/authority', Record<never, never>, Record<never, never>>,
    '/admin/authority/components/apis': RouteRecordInfo<'/admin/authority/components/apis', '/admin/authority/components/apis', Record<never, never>, Record<never, never>>,
    '/admin/authority/components/menus': RouteRecordInfo<'/admin/authority/components/menus', '/admin/authority/components/menus', Record<never, never>, Record<never, never>>,
    '/admin/operation/sysOperationRecord': RouteRecordInfo<'/admin/operation/sysOperationRecord', '/admin/operation/sysOperationRecord', Record<never, never>, Record<never, never>>,
    '/admin/user/user': RouteRecordInfo<'/admin/user/user', '/admin/user/user', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/person/person': RouteRecordInfo<'/person/person', '/person/person', Record<never, never>, Record<never, never>>,
    '/portal/': RouteRecordInfo<'/portal/', '/portal', Record<never, never>, Record<never, never>>,
    '/portal/about': RouteRecordInfo<'/portal/about', '/portal/about', Record<never, never>, Record<never, never>>,
    '/portal/article/[id]': RouteRecordInfo<'/portal/article/[id]', '/portal/article/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/portal/category/[id]': RouteRecordInfo<'/portal/category/[id]', '/portal/category/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/portal/contact': RouteRecordInfo<'/portal/contact', '/portal/contact', Record<never, never>, Record<never, never>>,
    '/substance/': RouteRecordInfo<'/substance/', '/substance', Record<never, never>, Record<never, never>>,
    '/substance/article/article': RouteRecordInfo<'/substance/article/article', '/substance/article/article', Record<never, never>, Record<never, never>>,
    '/substance/category/category': RouteRecordInfo<'/substance/category/category', '/substance/category/category', Record<never, never>, Record<never, never>>,
    '/substance/message/message': RouteRecordInfo<'/substance/message/message', '/substance/message/message', Record<never, never>, Record<never, never>>,
    '/substance/tag/tag': RouteRecordInfo<'/substance/tag/tag', '/substance/tag/tag', Record<never, never>, Record<never, never>>,
    '/substance/theme/theme': RouteRecordInfo<'/substance/theme/theme', '/substance/theme/theme', Record<never, never>, Record<never, never>>,
    '/substance/upload/upload': RouteRecordInfo<'/substance/upload/upload', '/substance/upload/upload', Record<never, never>, Record<never, never>>,
  }
}
